# Generated by Django 6.0.2 on 2026-03-05 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('agent', 'Agent'), ('landlord', 'Landlord')], default='landlord', max_length=15)),
                ('type', models.CharField(choices=[('single_room', 'Single_room'), ('bedsitter', 'Bedsitter'), ('double_room', 'Double_room'), ('one_bedroom', 'One_bedroom')], default='single_room', max_length=15)),
                ('picture', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('rent', models.DecimalField(decimal_places=2, max_digits=10)),
                ('deposit_required', models.BooleanField(default=True)),
                ('utilities_included', models.CharField(max_length=100)),
                ('total_units', models.IntegerField(default=0)),
                ('vacant_units', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
