# Generated by Django 6.0.2 on 2026-03-07 10:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('houses', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='picture',
        ),
    ]
